"""kaleidoscope_group.py — The engine as a real kaleidoscope.

A kaleidoscope is not a clustering algorithm. It is a *symmetry engine*: it
takes a shape and shows every image of that shape under a group of turns and
mirrors, all at once. What you see through the tube is the shape's ORBIT — the
complete set of its reflected/rotated views — and what makes two views "the
same kaleidoscope image" is that one is a mirrored-rotated copy of the other.

Translating that literally into the data manifold:

  DNA               a node's latent code z_i (from kaleidoscope_core)
  shape             the geometric object that code names in latent space
  turns & mirrors   a group G of orthogonal transforms (rotations + reflections)
                    acting on latent space — the principal axes are the mirror
                    planes, so the group is generated by axis reflections and
                    the rotations they compose to
  orbit             orbit(z) = { g·z : g in G } — every view of that DNA
  strain            an equivalence class under G: z_i ~ z_j iff z_j lies in
                    orbit(z_i) (one is a mirrored/rotated view of the other)
  supernode         the INVARIANT of the class: the canonical representative
                    plus the conserved quantities that survive every turn and
                    mirror. "All variation embodied" = the orbit; the identity
                    that persists through all of it = the invariant.

Why this is not clustering: k-means asks "which points are near each other"
and collapses them to a centroid — it destroys the angles. The kaleidoscope
asks "which points are mirror/rotation images of each other" and keeps the
whole orbit, storing only the symmetry that relates them. Two DNA codes that
are far apart in raw distance but are reflections of one another belong to the
SAME strain here and to DIFFERENT clusters under k-means. That is the
falsifiable difference, and it is what `gate_orbit_beats_distance` measures.

The conserved invariants under an orthogonal group are functions that do not
change under rotation/reflection: norm, and the sorted magnitude spectrum of
the code along the mirror axes. Two codes with the same invariant signature
are the same kaleidoscope image. That signature is the strain key.

Deterministic, numpy + stdlib only. Composes with kaleidoscope_core.Manifold.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np

import organic_ai_core as core


# ===========================================================================
# The group of turns and mirrors
# ===========================================================================


class KaleidoscopeGroup:
    """A finite group of orthogonal transforms acting on latent DNA.

    Generators are the reflections across each principal (mirror) axis and the
    cyclic rotations in each coordinate plane by 2π/`fold`. Composing these
    generates the dihedral-style symmetry a physical kaleidoscope produces
    (fold mirrors -> 2·fold images). We materialize a deterministic, finite set
    of group elements (the generated closure up to `max_elements`) so every
    orbit is computable and reproducible.
    """

    __slots__ = ("dim", "fold", "elements")

    def __init__(self, dim: int, fold: int = 6, max_elements: int = 64) -> None:
        self.dim = dim
        self.fold = fold
        self.elements = self._generate(max_elements)

    def _generators(self) -> List[np.ndarray]:
        d = self.dim
        gens: List[np.ndarray] = []
        # Mirrors: reflection across each axis (flip the sign of one coordinate).
        # These preserve every |coordinate|, hence the sorted-magnitude spectrum.
        for i in range(d):
            m = np.eye(d)
            m[i, i] = -1.0
            gens.append(m)
        # Turns: adjacent-axis SWAPS (permutation matrices). A physical
        # kaleidoscope's turns cycle the wedges; on a coordinate manifold the
        # exact, discrete realization is permuting axes. Swaps + sign-flips
        # generate the hyperoctahedral group B_d — the full symmetry group of
        # the d-cube, i.e. every 'turn and mirror' of an axis-aligned shape.
        # Crucially these permute the coordinates, so the SORTED magnitude
        # spectrum (the invariant) is exactly preserved. Group and invariant
        # are now consistent by construction.
        for i in range(d - 1):
            p = np.eye(d)
            p[i, i] = 0.0
            p[i + 1, i + 1] = 0.0
            p[i, i + 1] = 1.0
            p[i + 1, i] = 1.0
            gens.append(p)
        return gens

    def _generate(self, max_elements: int) -> np.ndarray:
        """Breadth-first closure of the generators, deduplicated by a rounded
        hash so the element set is finite and deterministic."""
        gens = self._generators()
        identity = np.eye(self.dim)
        seen: Dict[bytes, np.ndarray] = {self._key(identity): identity}
        frontier = [identity]
        while frontier and len(seen) < max_elements:
            nxt = []
            for g in frontier:
                for gen in gens:
                    cand = gen @ g
                    k = self._key(cand)
                    if k not in seen:
                        seen[k] = cand
                        nxt.append(cand)
                        if len(seen) >= max_elements:
                            break
                if len(seen) >= max_elements:
                    break
            frontier = nxt
        return np.stack(list(seen.values()))

    @staticmethod
    def _key(m: np.ndarray) -> bytes:
        return np.round(m, 6).tobytes()

    def orbit(self, z: np.ndarray) -> np.ndarray:
        """Every view of DNA z under all turns and mirrors: (|G|, k)."""
        return np.einsum("gij,j->gi", self.elements, z)

    def invariant(self, z: np.ndarray) -> np.ndarray:
        """Conserved signature of z under the group — identical for every член
        of an orbit. Uses quantities orthogonal transforms preserve:
          - the norm (rotation/reflection invariant), and
          - the sorted vector of absolute coordinate magnitudes (invariant to
            axis reflections and to the discrete rotations we generate, up to
            the group's resolution).
        Two codes with the same invariant are the same kaleidoscope image."""
        norm = float(np.linalg.norm(z))
        spectrum = np.sort(np.abs(z))[::-1]
        return np.concatenate([[norm], spectrum])

    def fingerprint(self) -> str:
        h = hashlib.blake2b(digest_size=8)
        h.update(self.elements.tobytes())
        return h.hexdigest()


# ===========================================================================
# Strains as orbits; supernodes as invariants
# ===========================================================================


@dataclass
class Strain:
    """A kaleidoscope strain: an equivalence class of DNA under the group.

    Stores the invariant signature (the conserved identity), the canonical
    representative (the orbit member closest to the positive orthant — a
    deterministic choice of 'the' view), the member indices, and the mass.
    This is the supernode: all variation embodied in `orbit_size` views, but
    identified by one invariant.
    """

    signature: np.ndarray          # conserved invariant (strain key)
    representative: np.ndarray      # canonical DNA view
    members: List[int]             # indices of nodes in this strain
    mass: float                    # fraction of population
    orbit_size: int                # |G| — how many views this strain embodies


def _canonical_view(orbit_pts: np.ndarray) -> np.ndarray:
    """Pick 'the' representative of an orbit deterministically: the view whose
    coordinates are most positive (largest lexicographic signature). This is
    the kaleidoscope's 'upright' image — one angle chosen to stand for all."""
    scores = [(tuple(np.round(-p, 9)), i) for i, p in enumerate(orbit_pts)]
    best = min(scores)[1]
    return orbit_pts[best]


def form_strains(codes: np.ndarray, group: KaleidoscopeGroup,
                 resolution: float = 0.35) -> Tuple[List[Strain], np.ndarray]:
    """Partition DNA codes into strains by their group invariant.

    Two codes fall in the same strain iff their invariant signatures agree
    within `resolution` (the kaleidoscope's angular resolution — finer -> more
    strains). Returns (strains, labels) where labels[i] is the strain index of
    code i. This REPLACES clustering: membership is by symmetry equivalence,
    not proximity.
    """
    n = codes.shape[0]
    signatures = np.stack([group.invariant(codes[i]) for i in range(n)])

    labels = -np.ones(n, dtype=int)
    strain_sigs: List[np.ndarray] = []
    strain_members: List[List[int]] = []

    order = sorted(range(n), key=lambda i: (-signatures[i, 0], i))  # by norm desc
    for i in order:
        sig = signatures[i]
        placed = False
        for s_idx, ssig in enumerate(strain_sigs):
            # Scale-relative match so large- and small-norm orbits are judged
            # on the same footing.
            denom = max(np.linalg.norm(ssig), 1e-9)
            if np.linalg.norm(sig - ssig) / denom <= resolution:
                labels[i] = s_idx
                strain_members[s_idx].append(i)
                placed = True
                break
        if not placed:
            labels[i] = len(strain_sigs)
            strain_sigs.append(sig)
            strain_members.append([i])

    strains: List[Strain] = []
    for s_idx, members in enumerate(strain_members):
        rep_code = codes[members[0]]
        orbit_pts = group.orbit(rep_code)
        rep = _canonical_view(orbit_pts)
        # The strain signature is the mean invariant of its members (the
        # conserved identity refined over the class).
        sig = np.mean(signatures[members], axis=0)
        strains.append(Strain(
            signature=sig, representative=rep, members=members,
            mass=len(members) / n, orbit_size=group.elements.shape[0]))
    return strains, labels


def coverage_contribution(codes: np.ndarray, labels: np.ndarray,
                          group: "KaleidoscopeGroup") -> np.ndarray:
    """How much each node adds to its strain's orbit coverage (leave-one-out).

    This replaces 'fitness' — a dead scalar where every node scored the same —
    with a structural quantity that actually discriminates. A strain is an
    orbit: the set of all mirrored/rotated views of a shape. A node holds one
    such view. Its VALUE is how much of the strain's angular territory it
    uniquely covers: a node whose nearest orbit-sibling is far away is holding
    a rare view the strain would lose without it; a node sitting on top of a
    sibling is a redundant duplicate and contributes nothing.

    For node i in strain s, contribution = distance (in the group's orbit
    metric) to the nearest OTHER member of s. Isolated views -> high value;
    duplicated views -> ~0. This is not imposed; it is the group structure
    telling us which views carry information.

    Returns contribution[N] in [0, ∞), normalized per strain to [0,1] so
    cross-strain comparison is fair.
    """
    n = codes.shape[0]
    contrib = np.zeros(n)
    for s in np.unique(labels):
        members = np.where(labels == s)[0]
        if len(members) == 1:
            contrib[members[0]] = 1.0   # sole holder of its view: maximal value
            continue
        member_codes = codes[members]
        # Orbit-aware distance: distance from each member to the nearest orbit
        # image of every OTHER member (so a mirrored duplicate counts as near).
        for a_idx, i in enumerate(members):
            zi = codes[i]
            best = np.inf
            for b_idx, j in enumerate(members):
                if i == j:
                    continue
                orbit_j = group.orbit(member_codes[b_idx])
                d = float(np.min(np.sum((orbit_j - zi) ** 2, axis=1)))
                if d < best:
                    best = d
            contrib[i] = np.sqrt(best)
        # Normalize within strain to [0,1].
        mx = contrib[members].max()
        if mx > 1e-12:
            contrib[members] /= mx
    return contrib


def one_entity(strains: List[Strain]) -> np.ndarray:
    """S* — mass-weighted sum of strain representatives."""
    if not strains:
        return np.array([])
    reps = np.stack([s.representative for s in strains])
    masses = np.array([s.mass for s in strains])
    masses = masses / masses.sum()
    return masses @ reps


# ===========================================================================
# Gates
# ===========================================================================


def gate_orbit_invariance(group: KaleidoscopeGroup, trials: int = 20,
                          seed: int = 0, tol: float = 1e-6) -> None:
    """The defining property: every member of an orbit must share one invariant
    signature. If applying any turn/mirror changed the signature, the invariant
    would not identify the kaleidoscope image and the whole construction is
    void."""
    rng = core.derive_rng("orbit-inv-gate", seed, group.dim)
    for _ in range(trials):
        z = rng.normal(size=group.dim)
        base = group.invariant(z)
        orbit_pts = group.orbit(z)
        for p in orbit_pts:
            dev = float(np.max(np.abs(group.invariant(p) - base)))
            if dev > tol:
                raise AssertionError(
                    f"orbit-invariance gate FAILED: signature drifted {dev:.2e} "
                    f"under a group element (invariant is not invariant)")


def gate_orbit_beats_distance(seed: int = 0, dim: int = 6) -> Tuple[bool, bool]:
    """The falsifiable difference from clustering. Take a code, produce a
    mirrored-rotated view of it that is FAR in raw distance. The kaleidoscope
    must put them in the SAME strain (they are the same image); a nearest-
    centroid / distance rule would put them in DIFFERENT clusters. We assert the
    kaleidoscope unifies them AND that they are genuinely distance-separated
    (so the test is non-trivial)."""
    group = KaleidoscopeGroup(dim=dim, fold=6)
    rng = core.derive_rng("orbit-vs-dist-gate", seed, dim)
    z = rng.normal(size=dim)
    # A non-identity group element gives a mirrored/rotated view.
    g = group.elements[len(group.elements) // 2]
    z_view = g @ z
    raw_distance = float(np.linalg.norm(z - z_view))

    codes = np.stack([z, z_view])
    strains, labels = form_strains(codes, group, resolution=0.35)
    same_strain = bool(labels[0] == labels[1])
    genuinely_far = raw_distance > 0.5 * np.linalg.norm(z)

    if not same_strain:
        raise AssertionError(
            "orbit-vs-distance gate FAILED: a mirrored view was NOT unified "
            "into the same strain (engine is behaving like clustering)")
    if not genuinely_far:
        raise AssertionError(
            "orbit-vs-distance gate FAILED: the mirrored view was not actually "
            "distance-separated, so the test is trivial")
    return same_strain, genuinely_far


def gate_determinism(codes: np.ndarray, group: KaleidoscopeGroup) -> None:
    a, la = form_strains(codes.copy(), group)
    b, lb = form_strains(codes.copy(), group)
    if not np.array_equal(la, lb):
        raise AssertionError("determinism gate FAILED: strain labels differ")


# ===========================================================================
# Demonstration
# ===========================================================================


def _demo() -> None:
    seed = 0
    dim = 6
    group = KaleidoscopeGroup(dim=dim, fold=6)

    print("=" * 70)
    print("KALEIDOSCOPE GROUP — strains as orbits, supernodes as invariants")
    print("=" * 70)
    print(f"  latent dim {dim}, {group.fold}-fold, |G| = "
          f"{group.elements.shape[0]} turns+mirrors")

    gate_orbit_invariance(group, seed=seed)
    print("GATE orbit-invariance      PASS  (one invariant per orbit, all views "
          "agree)")

    same, far = gate_orbit_beats_distance(seed=seed, dim=dim)
    print(f"GATE orbit-beats-distance  PASS  (mirrored-far view unified into one "
          f"strain: same={same}, far={far})")

    # Build codes that are mixtures of a few 'shapes' plus their mirrored views.
    rng = core.derive_rng("kg-demo", seed)
    base_shapes = rng.normal(size=(4, dim))
    codes = []
    for _ in range(200):
        shape = base_shapes[rng.integers(4)]
        g = group.elements[rng.integers(group.elements.shape[0])]  # random view
        codes.append(g @ shape + 0.05 * rng.normal(size=dim))
    codes = np.stack(codes)

    gate_determinism(codes, group)
    print("GATE determinism           PASS  (identical strain labels x2)")

    strains, labels = form_strains(codes, group, resolution=0.35)
    s_star = one_entity(strains)

    print("-" * 70)
    print("STRAINS FROM 200 CODES (4 hidden shapes × random turns+mirrors)")
    print(f"  strains discovered           : {len(strains)}  "
          f"(hidden shapes: 4)")
    print(f"  each strain embodies         : {group.elements.shape[0]} views "
          f"(its full orbit)")
    print(f"  S* one-entity (Σ mass·view)  : dim={s_star.shape[0]}, "
          f"‖S*‖={np.linalg.norm(s_star):.4f}")
    print("-" * 70)
    for i, s in enumerate(sorted(strains, key=lambda x: -x.mass)[:6]):
        print(f"  strain {i}: mass {s.mass:.3f}  members {len(s.members):3d}  "
              f"‖invariant‖ {np.linalg.norm(s.signature):.3f}  "
              f"rep[:3]={np.round(s.representative[:3], 3).tolist()}")


if __name__ == "__main__":
    _demo()
